# Generated by Django 6.0.3 on 2026-03-15 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.IntegerField(db_index=True)),
                ('text', models.CharField(max_length=500)),
                ('options', models.JSONField(default=list)),
                ('correct_index', models.IntegerField()),
            ],
        ),
    ]
