# Generated by Django 6.0.3 on 2026-03-15 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_category_remove_question_category_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='icon_url',
        ),
        migrations.RemoveField(
            model_name='category',
            name='image_url',
        ),
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='categories/icons/'),
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='categories/images/'),
        ),
    ]
