# Generated by Django 6.0.3 on 2026-03-15 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_remove_category_icon_url_remove_category_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_new',
            field=models.BooleanField(default=False),
        ),
    ]
